use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use serde::{Deserialize, Serialize};
use crate::storage::{
    global_env_file, instance_env_file, project_env_file, write_json_atomic,
};

pub const ENV_FILE_MARKER: &str = "# Generated by Cairn - edits are overwritten";

fn default_true() -> bool { true }

fn default_env_file_name() -> String { ".env".to_string() }

#[derive(Serialize, Deserialize, Clone)]
pub struct EnvVariable {
    pub id: String,
    pub key: String,
    #[serde(default)]
    pub value: String,
    #[serde(rename = "perInstance", default)]
    pub per_instance: bool,
    #[serde(default)]
    pub secret: bool,
    #[serde(default = "default_true")]
    pub enabled: bool,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct EnvFile {
    #[serde(default)]
    pub variables: Vec<EnvVariable>,
    #[serde(default)]
    pub overrides: HashMap<String, String>,
    #[serde(rename = "writeEnvFile", default = "default_true")]
    pub write_env_file: bool,
    #[serde(rename = "envFileName", default = "default_env_file_name")]
    pub env_file_name: String,
}

impl Default for EnvFile {
    fn default() -> Self {
        Self {
            variables: Vec::new(),
            overrides: HashMap::new(),
            write_env_file: true,
            env_file_name: default_env_file_name(),
        }
    }
}

#[derive(Serialize, Deserialize, Clone, Default)]
pub struct EnvFileStatus {
    pub exists: bool,
    pub managed: bool,
}

fn read_env(path: &Path) -> Result<EnvFile, String> {
    if !path.exists() { return Ok(EnvFile::default()); }
    let content = fs::read_to_string(path).map_err(|e| e.to_string())?;
    serde_json::from_str(&content).map_err(|e| e.to_string())
}

fn resolve_target(worktree_path: &str, file_name: &str) -> Result<PathBuf, String> {
    let name = file_name.trim();
    let invalid = name.is_empty()
        || name == "."
        || name == ".."
        || name.contains('/')
        || name.contains('\\');
    if invalid {
        return Err(format!("Invalid env file name: {file_name}"));
    }
    let dir = shellexpand::tilde(worktree_path).into_owned();
    Ok(Path::new(&dir).join(name))
}

fn is_managed(path: &Path) -> bool {
    let Ok(content) = fs::read_to_string(path) else { return false };
    content.lines().next().map(|l| l.trim_end() == ENV_FILE_MARKER).unwrap_or(false)
}

// ---------------------------------------------------------------------------
// Stored variables
// ---------------------------------------------------------------------------

#[tauri::command]
pub fn get_global_env() -> Result<EnvFile, String> {
    read_env(&global_env_file()?)
}

#[tauri::command]
pub fn save_global_env(state: EnvFile) -> Result<(), String> {
    write_json_atomic(&global_env_file()?, &state)
}

#[tauri::command]
pub fn get_project_env(project_id: String) -> Result<EnvFile, String> {
    read_env(&project_env_file(&project_id)?)
}

#[tauri::command]
pub fn save_project_env(project_id: String, state: EnvFile) -> Result<(), String> {
    write_json_atomic(&project_env_file(&project_id)?, &state)
}

#[tauri::command]
pub fn get_instance_env(project_id: String, instance_id: String) -> Result<EnvFile, String> {
    read_env(&instance_env_file(&project_id, &instance_id)?)
}

#[tauri::command]
pub fn save_instance_env(
    project_id: String,
    instance_id: String,
    state: EnvFile,
) -> Result<(), String> {
    write_json_atomic(&instance_env_file(&project_id, &instance_id)?, &state)
}

// ---------------------------------------------------------------------------
// Generated file in the worktree
// ---------------------------------------------------------------------------

#[tauri::command]
pub fn env_file_status(worktree_path: String, file_name: String) -> Result<EnvFileStatus, String> {
    let target = resolve_target(&worktree_path, &file_name)?;
    if !target.is_file() {
        return Ok(EnvFileStatus { exists: false, managed: false });
    }
    Ok(EnvFileStatus { exists: true, managed: is_managed(&target) })
}

#[tauri::command]
pub fn read_env_file(worktree_path: String, file_name: String) -> Result<String, String> {
    let target = resolve_target(&worktree_path, &file_name)?;
    if !target.is_file() { return Ok(String::new()); }
    fs::read_to_string(&target).map_err(|e| e.to_string())
}

#[tauri::command]
pub fn write_env_file(
    worktree_path: String,
    file_name: String,
    body: String,
    force: Option<bool>,
) -> Result<bool, String> {
    let target = resolve_target(&worktree_path, &file_name)?;
    if target.is_file() && !is_managed(&target) && !force.unwrap_or(false) {
        return Ok(false);
    }
    let mut content = String::from(ENV_FILE_MARKER);
    content.push('\n');
    if !body.is_empty() {
        content.push_str(&body);
        if !body.ends_with('\n') { content.push('\n'); }
    }
    if fs::read_to_string(&target).map(|existing| existing == content).unwrap_or(false) {
        return Ok(true);
    }
    fs::write(&target, content).map_err(|e| e.to_string())?;
    Ok(true)
}

#[tauri::command]
pub fn delete_env_file(worktree_path: String, file_name: String) -> Result<bool, String> {
    let target = resolve_target(&worktree_path, &file_name)?;
    if !target.is_file() || !is_managed(&target) { return Ok(false); }
    fs::remove_file(&target).map_err(|e| e.to_string())?;
    Ok(true)
}

#[tauri::command]
pub async fn ensure_env_ignored(worktree_path: String, file_name: String) -> Result<bool, String> {
    let dir = shellexpand::tilde(&worktree_path).into_owned();
    if !Path::new(&dir).is_dir() { return Ok(false); }

    let already = Command::new("git")
        .current_dir(&dir)
        .args(["check-ignore", "-q", "--", &file_name])
        .status()
        .map_err(|e| e.to_string())?
        .success();
    if already { return Ok(false); }

    let out = Command::new("git")
        .current_dir(&dir)
        .args(["rev-parse", "--path-format=absolute", "--git-common-dir"])
        .output()
        .map_err(|e| e.to_string())?;
    if !out.status.success() { return Ok(false); }
    let common = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if common.is_empty() { return Ok(false); }

    let exclude = Path::new(&common).join("info").join("exclude");
    if let Some(parent) = exclude.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    let existing = fs::read_to_string(&exclude).unwrap_or_default();
    if existing.lines().any(|l| l.trim() == file_name) { return Ok(false); }

    let mut next = existing;
    if !next.is_empty() && !next.ends_with('\n') { next.push('\n'); }
    next.push_str(&format!("{file_name}\n"));
    fs::write(&exclude, next).map_err(|e| e.to_string())?;
    Ok(true)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("cairn-env-{}-{}", name, std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn write_env_file_prepends_the_marker() {
        let dir = temp_dir("marker");
        let path = dir.to_string_lossy().to_string();

        assert!(write_env_file(path.clone(), ".env".into(), "A=1".into(), None).unwrap());

        let content = fs::read_to_string(dir.join(".env")).unwrap();
        assert_eq!(content, format!("{ENV_FILE_MARKER}\nA=1\n"));
    }

    #[test]
    fn write_env_file_refuses_a_foreign_file() {
        let dir = temp_dir("foreign");
        let path = dir.to_string_lossy().to_string();
        fs::write(dir.join(".env"), "A=kept\n").unwrap();

        assert!(!write_env_file(path.clone(), ".env".into(), "A=1".into(), None).unwrap());
        assert_eq!(fs::read_to_string(dir.join(".env")).unwrap(), "A=kept\n");

        let status = env_file_status(path.clone(), ".env".into()).unwrap();
        assert!(status.exists);
        assert!(!status.managed);
    }

    #[test]
    fn write_env_file_takes_a_foreign_file_over_when_forced() {
        let dir = temp_dir("takeover");
        let path = dir.to_string_lossy().to_string();
        fs::write(dir.join(".env"), "A=kept\n").unwrap();

        assert!(write_env_file(path.clone(), ".env".into(), "A=1".into(), Some(true)).unwrap());

        assert!(env_file_status(path, ".env".into()).unwrap().managed);
    }

    #[test]
    fn write_env_file_rewrites_its_own_file() {
        let dir = temp_dir("idempotent");
        let path = dir.to_string_lossy().to_string();

        write_env_file(path.clone(), ".env".into(), "A=1".into(), None).unwrap();
        assert!(write_env_file(path.clone(), ".env".into(), "A=2".into(), None).unwrap());

        let content = fs::read_to_string(dir.join(".env")).unwrap();
        assert_eq!(content, format!("{ENV_FILE_MARKER}\nA=2\n"));
        assert!(env_file_status(path, ".env".into()).unwrap().managed);
    }

    #[test]
    fn delete_env_file_only_removes_a_generated_file() {
        let dir = temp_dir("delete");
        let path = dir.to_string_lossy().to_string();
        fs::write(dir.join(".env"), "A=kept\n").unwrap();

        assert!(!delete_env_file(path.clone(), ".env".into()).unwrap());
        assert!(dir.join(".env").is_file());

        write_env_file(path.clone(), ".env.local".into(), "A=1".into(), None).unwrap();
        assert!(delete_env_file(path, ".env.local".into()).unwrap());
        assert!(!dir.join(".env.local").is_file());
    }

    #[test]
    fn resolve_target_rejects_a_name_leaving_the_worktree() {
        assert!(resolve_target("/tmp", "../escaped").is_err());
        assert!(resolve_target("/tmp", "sub/.env").is_err());
        assert!(resolve_target("/tmp", "  ").is_err());
    }
}
